# Generated by Django 6.0.4 on 2026-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('student', 'competition')},
        ),
        migrations.AddField(
            model_name='absence',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'سليم'), ('injured', 'مصاب')], default='healthy', max_length=10),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'وارد جديد'), ('sent', 'أُرسلت للطلبة'), ('completed', 'مكتملة')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('A', 'رياضي'), ('B', 'ثقافي')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to='schedules/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='absence',
            name='injury_status',
        ),
    ]
