# Generated by Django 6.0.4 on 2026-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_absence_unique_together_absence_health_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='absence',
            name='injury_description',
            field=models.TextField(blank=True, verbose_name='وصف الإصابة/التعب'),
        ),
        migrations.AddField(
            model_name='absence',
            name='injury_status',
            field=models.CharField(choices=[('healthy', 'سليم'), ('injured', 'مصاب'), ('sick', 'تعبان/مريض')], default='healthy', max_length=10, verbose_name='الحالة الصحية'),
        ),
        migrations.AddField(
            model_name='absence',
            name='is_justified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='return_confirmed',
            field=models.BooleanField(default=False, verbose_name='تأكيد العودة'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ العودة'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'وارد جديد'), ('sent', 'أرسلت للطلبة'), ('completed', 'مكتملة')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.CharField(max_length=100, verbose_name='النشاط'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood',
            field=models.CharField(max_length=5, verbose_name='زمرة الدم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('A', 'رياضي'), ('B', 'ثقافي')], max_length=1, verbose_name='نوع النشاط'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=12, unique=True, verbose_name='رقم التسجيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to='schedules/', verbose_name='الجدول الزمني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(max_length=200, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
        migrations.RemoveField(
            model_name='absence',
            name='health_status',
        ),
    ]
