# Generated by Django 6.0.4 on 2026-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_absence_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='ai_analysis_report',
            field=models.TextField(blank=True, null=True, verbose_name='AI Analysis Report'),
        ),
    ]
