# Generated by Django 6.0.4 on 2026-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_absence_ai_analysis_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('student', 'competition')},
        ),
        migrations.AddField(
            model_name='absence',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='medical_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='medical_reports/'),
        ),
        migrations.AddField(
            model_name='absence',
            name='medical_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='medical_reports/'),
        ),
        migrations.AddField(
            model_name='absence',
            name='medical_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='medical_reports/'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='injury_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='injury_status',
            field=models.CharField(choices=[('healthy', 'سليم'), ('injured', 'مصاب'), ('sick', 'مريض')], default='healthy', max_length=10),
        ),
        migrations.AlterField(
            model_name='absence',
            name='return_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absence',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'وارد جديد'), ('sent', 'أُرسلت للطلبة'), ('completed', 'مكتملة')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('A', 'رياضي'), ('B', 'ثقافي')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to='schedules/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='absence',
            name='ai_analysis_report',
        ),
    ]
