# Generated by Django 6.0.4 on 2026-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_absence_unique_together_absence_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم (عربي)'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (Français)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اللقب (عربي)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom (Français)'),
        ),
    ]
